
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: dbdesafio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"


  # Opcional: pgAdmin para gerenciar o banco de dados
  
