POST http://localhost:3333/courses
Content-Type: application/json

{
     "title": "Curso de Docker"
}
###

GET http://localhost:3333/courses


###
GET http://localhost:3333/courses/adca091b-6bd3-4626-ac32-dca031fb4e59